name: Docker Build Image
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello world
        run: echo "Hello World"
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cleverse-backend-project-api:${{github.sha}}
      - name: Echo dir
        run: ls -lah
