name: Docker Build Image
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello world
        run: echo "Hello World"
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Echo dir
        run: ls -lah
