name: Docker Build Image
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello world
        run: echo "Hello World"
      - name: checkout
        uses: actions/checkout@v4
      - name: Echo where
        run: pwd
      - name: Echo dir
        run: ls -lah
